### ISSUE TITLE
Upgrade resets inspection settings previously set

### ISSUE THREAD

**Issue by brazenvoid** [hammer-tools/php-hammer#10] opened 2023-02-24 02:05 UTC
Essentially whenever the plugin upgrades to a newer versions, all inspection settings I have customized will get reset to your defaults. Like if I have disabled some of the inspections included in your package, they will be enabled again after the reset. 

This has happened twice now. Recently I updated from 1.19 to 1,21 and the settings got reset again. Which you must understand is a frustrating thing to find each and every inspection yet again and restore the settings manually one by one. 

Am on the latest PHPStorm 2022.3.

**Comment by rentalhost** [comment] 2023-02-24 03:36
In fact, it seems to me a big problem. I never noticed this happening. It only happens with this plugin, correct? This week I'm going to inspect the cause to try to find the problem and come up with a solution for it.

**Comment by brazenvoid** [comment] 2023-02-24 03:37
Yes, it only happens with your plugin.

**Comment by rentalhost** [comment] 2023-02-24 03:54
Thanks, I will check that before a new release!

**Comment by rentalhost** [comment] 2023-05-21 01:26
@brazenvoid I tried to identify the cause of this issue to the best of my ability. Unfortunately, I couldn't obtain any precise results and couldn't reproduce it myself. It's possible that the problem occurred due to specific changes between versions 0.19 and 0.21. However, we have a new version coming soon, and I would appreciate your feedback if this issue occurs again. For now, I will close this issue, but please feel free to comment here if the problem persists. We expect the new version to be released within approximately 3 days.

**Comment by rentalhost** [comment] 2023-05-21 04:07
**Implemented in version 0.22.0:**

Hello @brazenvoid, the new **version 0.22.0** has just been released and is available for direct download from the **[Releases](https://github.com/hammer-tools/php-hammer/releases/tag/0.22.0)** page. This update will be available on the **[Jetbrains Market](https://plugins.jetbrains.com/plugin/19515-php-hammer)** in approximately three days if you prefer to wait.

**This version comes with some new features, now totaling 51 inspections:**

- Support for the **new PhpStorm 2023.2 EAP** (_minimum version from now on_);
- **Your suggestions:** inspection to suggest strict comparison when possible;
- **Your suggestions:** Inspection to suggest the use of non-deprecated functions (e.g., `mt_rand()` to `random_int()`);
- Additional feature: add missing _semicolon_ when saving a PHP file;
- Other minor improvements.

Thank you for taking the time to report this issue. As mentioned earlier, I was unable to reproduce it. If possible, please install this new version or wait for its release on the marketplace and let me know if the problem persists.

**Comment by brazenvoid** [comment] 2023-08-18 08:26
The latest version 0.23.0 reset my changes.

**Comment by rentalhost** [comment] 2023-08-18 16:38
That's weird! There is no change in the settings part between version 0.22 to 0.23 that would justify this. What kind of setting do you say you are resetting, exactly? Because it seems to me more a PhpStorm bug, however, as you said that it only happens with this plugin, it is quite suspicious. I really don't understand how to proceed.

**Comment by brazenvoid** [comment] 2023-08-18 19:18
I am referring to the inspection settings I customize, like disabling some of them or changing warning levels. Those get reset to defaults, like all inspections get enabled and their warning levels are restored after update.

**Comment by rentalhost** [comment] 2023-08-18 20:51
It's really quite weird. Well, next time, if you can, I'll ask you to send me a backup of your current inspections and php-hammer settings (something PhpStorm itself generates), and then I'll update and ask for a new backup. So I can try to understand what's changing, if it's a problem with php-hammer specifically or else in PhpStorm itself (they recently worked on a similar problem of missing inspection information, but it looks like it's already fixed).

**Comment by rentalhost** [comment] 2023-10-02 17:02
Hi @brazenvoid, a new release will be released in a few days (maybe 2). If possible, please generate a backup of your settings so that I can analyze the before and after, to understand what is happening in your case, if that is feasible for you.

**Comment by brazenvoid** [comment] 2023-10-02 17:08
Ok I will.

**Comment by rentalhost** [comment] 2023-10-02 22:24
Thank you for taking the time to report this issue. The fix has been implemented in version **0.24.0** and is available on the **[Releases](https://github.com/hammer-tools/php-hammer/releases)** page for manual installation. Alternatively, you can wait for the official release on the **JetBrains Marketplace**, which should happen in approximately 3 days.

- **In response to your issue:** there's no new information regarding it in terms of programming. However, after you updating to this new version, please check if the problem still occurs (my only hope is that the JetBrains team might have fixed the issue on their end). Nevertheless, if the problem happens again, please send me your backups from before and after so that I can try to understand the reason.

**Comment by brazenvoid** [comment] 2023-10-05 07:18
I did encounter the same problem again but the settings backup doesn't store the actual settings for some reason haha. So frankly that mechanism can't be used to ascertain the issue.

**Comment by rentalhost** [comment] 2023-10-05 18:47
Well, it looks like we have **2 cases now** (#31)... I'll need to investigate further, perhaps rewrite all the programming regarding configurations and look for solutions in other plugins.

**Comment by rentalhost** [comment] 2023-10-05 18:48
One of the quasi-possibilities is: I always keep all the settings in the "default" settings, and this makes it difficult for me to see the problem. I'll try to create new builds with custom settings and try to understand what's going on behind all this. It's quite sinister.

**Comment by rentalhost** [comment] 2023-10-05 19:25
When you @brazenvoid and @caricare2 say "customizations are lost", do you mean only those inspections that have "customizations" or the activation/deactivation of an entire inspection by itself? In other words, it is as if you had just installed the plugin and returned to using 100% of the default values (the inspections themselves being active as defaults in themselves, but also including the inspection options returning to default values). This might help me get an idea.

Case 1:

![image](https://github.com/hammer-tools/php-hammer/assets/421851/973a1b04-69e2-4887-a791-ae2aee78f6dc)

Case 2:

![image](https://github.com/hammer-tools/php-hammer/assets/421851/b0c2fec4-913f-432b-b04e-38af6393e83b)

**Comment by rentalhost** [comment] 2023-10-05 19:27
Or even... is there any inspection that you remember precisely having "reset"? Perhaps there may be a name conflict between the other existing inspections, and perhaps only some are presenting a problem.

**Comment by brazenvoid** [comment] 2023-10-05 19:36
I don't think I ever customize any of your inspections anymore, i deem it a huge hassle as they get reset after update. 

For example, I always disable the default null or the add parent method inspection. Its too early after the reset, its going to take me a while to stumble upon all the frustrating ones, haha.

**Comment by rentalhost** [comment] 2023-10-05 19:48
@brazenvoid My initial suggestion is to avoid customizing for now, give me some time, I will try to resolve this today. Hopefully, we'll have this fully resolved and you'll be able to customize the extension again without any major issues later. (Possibly the next update may reset again one last time, depending on the cause of the problem. I'm still investigating.)

From what you said, it seems that all settings are in fact reset. It's a good start to try to understand what's going on...

**Comment by caricare2** [comment] 2023-10-05 19:53
If it helps I can give you an exact list of my customizations, or export a copy of my inspection settings. We're actually working on a project to standardize our inspections across our team so I have been keeping notes on all of them (which also thankfully meant it was easier to figure out what was changed).

It did seem as if it had reverted everything to the default values from a fresh install- I had several inspections I had disabled which were re-enabled, some I had changed the severity on which reverted to the original severity, and some where I had customized one of the options within the inspection that had changed back to the default options.

**Comment by rentalhost** [comment] 2023-10-05 19:55
@caricare2 It would be great, it would help to understand the problem better. For now, I'm taking a look at the implementation and trying to make the problem happen in a practical way. It would also be nice to know what additional extensions you have installed, perhaps one is causing a conflict.

**Comment by caricare2** [comment] 2023-10-05 20:08
[cari_inspections.txt](https://github.com/hammer-tools/php-hammer/files/12822820/cari_inspections.txt)

I had to rename the XML file to a .txt to include it here, they don't allow XML files. This is the exported list of my inspections. If you want me to give you a text list of my customizations I can do that as well.

I am using several plugins. The inspection related ones are PHPClean, Php Inspections (EA Extended). I doubt any of the other ones would be related as they are more UI focused but let me know if you need that list as well.

**Comment by rentalhost** [comment] 2023-10-05 20:13
@caricare2 I could suspect a conflict regarding Php Inspections (EA Extended), since it was the inspiration for this project and possibly the configuration nomenclatures are the same (internally, the configuration names end with "`Inspection`", and I was hoping PhpStorm would store it in a smarter way, like using the full configuration name instead of the short name). And perhaps during the plugin update PhpStorm notices a conflict between the 2 projects and resets the conflicting settings (and possibly all settings). I'll try to inspect something along these lines.

**Comment by rentalhost** [comment] 2023-10-05 20:42
Well, I just checked, and none of the names used in this plugin are also used by EA Extended (at least the non-Ultimate version). So, back to square one. I also wasn't able to replicate the problem, simulating a new version, etc.

**Comment by rentalhost** [comment] 2023-10-05 21:12
Anyway, maybe we won't have a solution today... But I'm trying to get in touch with the Jetbrains team and community of plugin developers to give me some insight. In the meantime, barring some critical failure (other than this one), I will avoid releasing new updates.

**Comment by rentalhost** [comment] 2023-10-16 18:57
@caricare2 Could you send me your "about" (Help / About / Copy and Close) with all the extensions installed? So maybe I can better identify the problem. Are you using any 3rd party extension that manages your settings, in addition to those provided by Jetbrains itself, for example?

I [**reported the problem**](https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1696540897732679) on Jetbrains Platform Slack, but no news yet.

**Comment by caricare2** [comment] 2023-10-16 19:04
Here's the about contents with personal information removed. I'm not using any extensions that manage my settings that I'm aware of.

PhpStorm 2023.2.2
Build #PS-232.9921.55, built on September 15, 2023
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    Dummy Text Generator (1.2.0)
    String Manipulation (9.11.3)
    com.github.ioannuwu.inline (1.3.0)
    com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
    com.funivan.idea.phpClean (2023.04.01)
    de.espend.idea.php.annotation (9.4.0)
    net.rentalhost.plugins.php.hammer (0.24.0)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    izhangzhihao.rainbow.brackets (2023.3.6)
    com.dmarcotte.handlebars (232.8660.88)
    com.clutcher.comments_highlighter (2023.7.14)
    zielu.gittoolbox (500.0.21+222)

**Comment by rentalhost** [comment] 2023-10-17 00:11
I have not yet found a solution to this problem, but I have not given up on finding one. The new **version 0.25.0** is available at [**Releases**](https://github.com/hammer-tools/php-hammer/releases) page, but **it will not be released on the Marketplace yet**, at least until I find a solution or, eventually, if I don't find one... give up (**I hope this doesn't happen**).

**Comment by rentalhost** [comment] 2023-10-17 15:38
@caricare2 @brazenvoid I've released a new **version 0.25.1** on the [**Releases**](https://github.com/hammer-tools/php-hammer/releases) page with some minor modifications regarding the internal structure of the [plugins.xml](https://github.com/hammer-tools/php-hammer/commit/d23a9c97a24e4c95af3f6771752005f2f762a8a4), removing Unicode characters (which might be causing the problem, _veeeeery maybe_). I'd appreciate it if at least one of you could test it, but before doing so, please make a backup of the inspections (via **Settings / Inspections / Export**) BEFORE and AFTER installing the update. If the issue persists, kindly send me both files, please. I'd like to try to understand what's happening in the meantime.

**Comment by caricare2** [comment] 2023-10-18 01:35
I would be happy to test it, but I'm not sure how to install the plugin manually, I've only ever installed plugins from the Marketplace. I see there is an option to install from disk, and I can download the files, but I'm not really sure what I select when installing from disk and if more steps are required.

**Comment by rentalhost** [comment] 2023-10-18 04:07
@caricare2 You just need install from the disk, go to Downloads folder and select the downloaded release. So you be asked to restart IDE, do it and all is done. Remember to backup Inspections before and after the process, please! :)

**Comment by caricare2** [comment] 2023-10-18 05:51
Good news! It looks like my settings stayed this time. The reason I asked about how to install was that there were 6 different jar files in the directory so I wasn't sure which was the right one, but I loaded instrumented-php-hammer-0.25.1.jar and that worked.

**Comment by rentalhost** [comment] 2023-10-18 14:24
@caricare2 You should use entire .zip, no internal contents files directly. I will upload to the Marketplace, I hope it doesn't break anything else!. hehe

**Comment by rentalhost** [comment] 2023-10-18 14:36
Taking your report into account, I will close this issue and hope it's permanent. But feel free to request a reopening if the problem occurs again.

**Comment by rentalhost** [comment] 2023-10-18 16:21
@brazenvoid Nice! If any issues occur from now on, they are probably related to installation via the Marketplace, and only Jetbrains can provide a solution. I hope that won't be necessary.

Regarding the crashes, if possible, can you provide a code that reproduces the issue? Or use the "Report" option in the crash dialog. If it's a platform issue, the report will reach me via Sentry. Ideally, though, a sample code that causes the crash would be most helpful, so I can personally see if there's anything I can do to improve it.

**Comment by brazenvoid** [comment] 2023-10-18 16:26
`public static function header(string $heading, string $description = '', array|string|BaseComponent $children = []): static`

Well its in a very deep location in my presentation architecture, to get you a working sample code would be giving you the whole app...

**Comment by rentalhost** [comment] 2023-10-18 17:17
@brazenvoid Could you copy the error track?

**Comment by rentalhost** [comment] 2023-10-18 17:51
@brazenvoid I received the report via Sentry. You mean this exception occurs when opening the file even if you don't apply the quick fix, don't you?

**Comment by brazenvoid** [comment] 2023-10-18 17:53
Yes, just as the file is opened, the exception comes up.

**Comment by rentalhost** [comment] 2023-10-18 18:02
@brazenvoid Great, I'll try an implementation here to suppress the error using the available SDK solutions (without using try/catch). However, if that doesn't work, it would be best to have a minimal reproducible code. That way, I can test whether the solution works or not before release.

An update will be available soon.

**Comment by caricare2** [comment] 2023-10-18 22:48
Thanks for the clarification- I reloaded it again with the zip- it just didn't occur to me that it was meant to be loaded as the entire bundle. I didn't have any issues after reloading it. Thank you for fixing it!

**Comment by caricare2** [comment] 2023-10-20 15:56
Bad news, I just upgraded to 0.26.0 through PHPStorm today and it reset my settings again. I did notice when upgrading that it said something about "unloading PHPHammer" before it told me to restart PHPStorm. I wonder if somehow that might be a factor in why it loses the settings, but I'm not sure.

Thankfully I still have my saved settings from the previous upgrade so I was able to restore them, but it looks like this problem is not resolved (it may be significant that it didn't happen when I loaded the previous release from a file).

**Comment by rentalhost** [comment] 2023-10-20 17:13
@caricare2 That's what I was afraid of... The only remaining option is some issue with the autosync of settings. Is it enabled? If so, maybe for the next update, I'll let you know to disable it and see if that solves the problem. But I believe, in the end, it's an issue with Jetbrains and not the plugin specifically.

**Comment by caricare2** [comment] 2023-10-20 17:28
I'm not using autosync. Mostly I'm concerned right now that we're going to get our whole team started using this set of inspections and if they have to reload the settings every time there's an upgrade, that's going to be a problem . I'm not sure if it will affect everyone though. Thanks for looking into it.

**Comment by rentalhost** [comment] 2023-10-20 17:39
@caricare2 It would be interesting if someone else from your team could try it before everyone uses it to see if they will be affected like you. It might be a problem with your installation as well; I can't say why. If it affects everyone, it would indeed be a problem. Do you think you can perform this test on your end?

**Comment by rentalhost** [comment] 2023-10-20 22:59
A new version will be released soon. I suggest you make a backup. I really don't know how to help anymore. My last idea would be to suggest reinstalling PhpStorm (back up your settings before) and trying again. It seems that the problem occurs exclusively when the plugin is installed via the Marketplace, which is quite, quite strange.

**Closed by rentalhost** 2023-10-20 22:59 UTC
Labels: bug, critical, investigating, blocking
